# Vector Ops

In [2]:
import numpy as np

In [3]:
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])

In [4]:
print("Addition:", vector1+vector2)
print("Subtraction:", vector1-vector2)
print("Multiplication:", vector1*vector2)
print("Dot Product:", np.dot(vector1,vector2) )
print("Division:", vector1/vector2)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Dot Product: 130
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [5]:
angle = np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print("Angle between vectors:", np.degrees(angle))

Angle between vectors: 15.214413958603176


In [6]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], #paradise biryani
    [2, 120000, 140000, 160000, 190000], #beijing bites
    [3, 200000, 230000, 260000, 300000], #pizza hub
    [4, 180000, 200000, 220000, 250000], # burger point
    [5, 160000, 180000, 200000, 220000] #chai point
])

print("====== Zomato Sales Data ======")
print(sales_data)



====== Zomato Sales Data ======
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 200000 220000 250000]
 [     5 160000 180000 200000 220000]]


In [7]:
restaurant_types = np.array(['biryani', 'beijing', 'pizza', 'burger', 'chai'])
vectorized_upper = np.vectorize(str.upper)
print(vectorized_upper(restaurant_types))

['BIRYANI' 'BEIJING' 'PIZZA' 'BURGER' 'CHAI']


In [8]:
# Broadcast

monthly_avg = sales_data[:,1:] / 12
print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         16666.66666667 18333.33333333 20833.33333333]
 [13333.33333333 15000.         16666.66666667 18333.33333333]]
